#### 1. Create a null vector of size 10 but the fifth value which is 1.

In [1]:
import numpy as np
arr = np.zeros(10)
arr[4]=1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 2. Create a vector with values ranging from 10 to 49.

In [2]:
arr = np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 3. Create a 3x3 matrix with values ranging from 0 to 8

In [3]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [4]:
arr = np.array([1,2,0,0,4,0])
np.nonzero(arr)

(array([0, 1, 4], dtype=int64),)

#### 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [5]:
arr = np.random.randint(100,size=(10,10))
print("Orignal Matrix :",arr)
print("\nMinimum Number :",np.min(arr))
print("\nMaximum Number :",np.max(arr))

Orignal Matrix : [[ 2  1 36 98 39 16 33 46 46 58]
 [97  1 66 71 51  8  6 10 39 28]
 [98 36 76 75 38 33 77 14 47 96]
 [57 32 39 91 74 30  5 54 94 55]
 [61 73 61 66 71 63 90 60 85 13]
 [39 16 82 52 59 15 38 76 83 64]
 [49 57 61 60 51 91 18  0 69 25]
 [31 50 13 85 97 54 10 84 24 13]
 [46 35 12 46 77 54 83 37 39 97]
 [20 31 85  9 83 96 78 24 25 10]]

Minimum Number : 0

Maximum Number : 98


#### 6. Create a random vector of size 30 and find the mean value.

In [6]:
arr = np.random.randint(30,size=30)
print(arr)
print("\nMean :",np.mean(arr))

[27 18 13 11  9  0  6  5 16  6 23 27  4 12 16 16 25 20  5  9 25 23 21 16
 26 17 11  9 18  0]

Mean : 14.466666666666667
